# Exercício Python 009: Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada.

n=int(input('Digite um numero e lhe darei sua taboada: '))

n1=(n*1)
n2=(n*2)
n3=(n*3)
n4=(n*4)
n5=(n*5)
n6=(n*6)
n7=(n*7)
n8=(n*8)
n9=(n*9)
n10=(n*10)

print('='*15)
print('{} x {:2} = {}'.format(n, 1, n1))
print('{} x {:2} = {}'.format(n, 2, n2))
print('{} x {:2} = {}'.format(n, 3, n3))
print('{} x {:2} = {}'.format(n, 4, n4))
print('{} x {:2} = {}'.format(n, 5, n5))
print('{} x {:2} = {}'.format(n, 6, n6))
print('{} x {:2} = {}'.format(n, 7, n7))
print('{} x {:2} = {}'.format(n, 8, n8))
print('{} x {:2} = {}'.format(n, 9, n9))
print('{} x {:2} = {}'.format(n, 10, n10))
print('='*15)
